name: Dev Snowflake Pipeline

on:
  push:
    branches:
      - cjh-research
  workflow_dispatch:

jobs:
  snowflake-migration:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cryptography snowflake-connector-python

      # Step 4: Azure Login
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Step 5: Fetch Secrets from Azure Key Vault
      - name: Fetch Snowflake secrets from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: "kv-dev"
          secrets: |
            SNOWFLAKE_PRIVATE_KEY_BASE64
            SNOWFLAKE_PRIVATE_KEY_PASSPHRASE
            SNOWFLAKE_USER
            SNOWFLAKE_ACCOUNT

      # Step 6: Export Secrets to GitHub Runner Environment
      - name: Configure secret environment variables
        run: |
          echo "SNOWFLAKE_PRIVATE_KEY_BASE64=${{ steps.keyvault.outputs.SNOWFLAKE_PRIVATE_KEY_BASE64 }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=${{ steps.keyvault.outputs.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ steps.keyvault.outputs.SNOWFLAKE_USER }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_ACCOUNT=${{ steps.keyvault.outputs.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV

      # Step 7: Run Snowflake SQL Migrations
      - name: Execute Migrations on Snowflake
        run: |
          python scripts/sql-runner.py sql/migrations

      # Step 8: Post-Check (Optional)
      - name: Post-Migration Check (Query Test)
        run: |
          echo "Running post-migration queries..."
          # Optional verification step to validate migrations.
